apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flows-documents
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flows-documents
    spec:
      containers:
      - name: flows-documents
        image: 192.168.1.10:5000/flows-documents:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /config.json
          name: config
          subPath: config.json
        tty: true
      volumes:
      - name: config
        configMap:
          name: flows-documents-config
          items:
          - key: config.json
            path: config.json
