apiVersion: v1
kind: Service
metadata: 
  name: flows-documents-service
  labels: 
    app: flows-documents
spec:
  ports:
    - port: 8085
      targetPort: 8080
  selector:
    app: flows-documents
  type: LoadBalancer
  externalIPs:
    - 0.0.0.0
