apiVersion: v1
data:
  config.json: |
    {
        "service": {
            "port": 8080
        },
        "database": {
            "host": "192.168.1.10",
            "name": "signingDatabase",
            "collection": "signatures",
            "collection_keys": "userKeys"
        },
        "remotes": {
            "users": "http://192.168.124.50:8080",
            "documents": "http://192.168.124.50:8081"
        }
    }
kind: ConfigMap
metadata:
  name: signing-config
