apiVersion: v1
kind: Service
metadata: 
  name: signing-service
  labels: 
    app: signing
spec:
  ports:
    - port: 8084
      targetPort: 8080
  selector:
    app: signing
  type: LoadBalancer
  externalIPs:
    - 0.0.0.0
