apiVersion: v1
kind: Service
metadata: 
  name: desktop-service
  labels: 
    app: desktop
spec:
  ports:
    - port: 8086
      targetPort: 8080
  selector:
    app: desktop
  type: LoadBalancer
  externalIPs:
    - 0.0.0.0
