apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: 192.168.1.10:5000/users:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /config.json
          name: config
          subPath: config.json
        tty: true
      volumes:
      - name: config
        configMap:
          name: users-config
          items:
          - key: config.json
            path: config.json
