apiVersion: v1
kind: Service
metadata: 
  name: users-service
  labels: 
    app: users
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: users
  type: LoadBalancer
  externalIPs:
    - 0.0.0.0
