mongo:
    image: mongo
    volumes:
        - "/var/db:/data/db"
users:
    image: localhost:5000/users:stable
    links:
        - "mongo:users-database-mongo"
    ports:
        - "8081:8080"
documents:
    image: localhost:5000/documents:stable
    links:
        - "mongo:documents-database-mongo"
        - "users:users"
    ports:
        - "8080:8080"
groups:
    image: localhost:5000/groups:stable
    links:
        - "mongo:groups-database-mongo"
        - "users:users"
    ports:
        - "8082:8080"
