apiVersion: v1
kind: Service
metadata: 
  name: mongo-service
  labels: 
    app: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
  type: LoadBalancer
  externalIPs:
    - 0.0.0.0
