apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: documents
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: documents
    spec:
      containers:
      - name: documents
        image: 192.168.1.10:5000/documents:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /config.json
          name: config
          subPath: config.json
        tty: true
      volumes:
      - name: config
        configMap:
          name: documents-config
          items:
          - key: config.json
            path: config.json
