apiVersion: v1
kind: Service
metadata: 
  name: documents-service
  labels: 
    app: documents
spec:
  ports:
    - port: 8081
      targetPort: 8080
  selector:
    app: documents
  type: LoadBalancer
  externalIPs:
    - 0.0.0.0
