apiVersion: v1
kind: Service
metadata: 
  name: flows-service
  labels: 
    app: flows
spec:
  ports:
    - port: 8083
      targetPort: 8080
  selector:
    app: flows
  type: LoadBalancer
  externalIPs:
    - 0.0.0.0
