apiVersion: v1
data:
  config.json: |
    {
        "service": {
            "port": 8080
        },
        "database": {
            "host": "192.168.1.10",
            "name": "groupsDatabase",
            "collection": "groups"
        },
        "remotes": {
            "users": "http://192.168.124.50:8080"
        }
    }
kind: ConfigMap
metadata:
  name: groups-config
