apiVersion: v1
kind: Service
metadata: 
  name: groups-service
  labels: 
    app: groups
spec:
  ports:
    - port: 8082
      targetPort: 8080
  selector:
    app: groups
  type: LoadBalancer
  externalIPs:
    - 0.0.0.0
